### PR TITLE
Create calamari-7but.sh

### PR DESCRIPTION
**Pull request by dbkinder**
MinnowBoard MAX/Calamari GPIO bash-script test file for reading the buttons and updating the 7-segment display with a hex counter (0-F) that decrements for presses from button 1 (left), increments for button 3 (right), and resets to 0 for button 2 (middle).

### CODE REVIEW

**Comment by warthog9** [comment]
Did we get the space / tabs thing resolved so this can get merged?

**Comment by dbkinder** [comment]
No.  I didn't work on this again.  Do you still want this example?

**Comment by dbkinder** [comment]
pr abandoned

**Comment by warthog9** [comment]
End of an era

**Pull request closed without merging**
