### PR TITLE
modules: Add i2c device instantiator

### PR DESCRIPTION
**Pull request by savoca**

### CODE REVIEW

**Comment by savoca** [comment]
@dvhart

**Comment by savoca** [comment]
Team seems to have abandoned this repository.

**Comment by faux123** [comment]
That's unfortunate.

**Comment by prpplague** [comment]
i think dvhart has been a little busy last week... i will ping him on this

**Comment by dvhart** [comment]
Sorry folks, December was a rough one. I'll get to this tonight.

**Comment by dvhart** [comment]
@savoca if you would like to resubmit, I'll be happy to pull.

**Pull request closed without merging**
